#!/bin/bash
# =============================================================================
# verify-deployment.sh - Post-Deploy Verification Script
# =============================================================================
# Auto-generated by Terraform
# Validates deployment by checking network, SSH, and application layer
# Exit code: 0 = success, 1 = failure
# =============================================================================

set -euo pipefail

# Variables from Terraform
VM_IP="${vm_ip}"
ADMIN_USERNAME="${admin_username}"

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Counters
TOTAL_CHECKS=0
PASSED_CHECKS=0
FAILED_CHECKS=0

# =============================================================================
# Helper Functions
# =============================================================================

print_header() {
    echo ""
    echo "=========================================="
    echo "  Post-Deploy Verification"
    echo "  VM: $VM_IP"
    echo "=========================================="
    echo ""
}

check_pass() {
    local check_name="$1"
    echo -e "$${GREEN}[PASS]$${NC} $check_name"
    PASSED_CHECKS=$((PASSED_CHECKS + 1))
    TOTAL_CHECKS=$((TOTAL_CHECKS + 1))
}

check_fail() {
    local check_name="$1"
    local suggestion="$2"
    echo -e "$${RED}[FAIL]$${NC} $check_name"
    if [ -n "$suggestion" ]; then
        echo -e "       $${YELLOW}Suggestion:$${NC} $suggestion"
    fi
    FAILED_CHECKS=$((FAILED_CHECKS + 1))
    TOTAL_CHECKS=$((TOTAL_CHECKS + 1))
}

# =============================================================================
# Network Layer Checks
# =============================================================================

check_network_ping() {
    echo "Checking network layer..."
    if ping -c 3 -W 5 "$VM_IP" > /dev/null 2>&1; then
        check_pass "Network: VM responds to ping"
    else
        check_fail "Network: VM does not respond to ping" \
            "Check if VM is running in Azure Portal and NSG allows ICMP"
    fi
}

# =============================================================================
# SSH Layer Checks
# =============================================================================

check_ssh_port() {
    echo "Checking SSH layer..."
    
    # Try nc (netcat) first, fallback to telnet if nc not available
    if command -v nc > /dev/null 2>&1; then
        if nc -z -w5 "$VM_IP" 22 > /dev/null 2>&1; then
            check_pass "SSH: Port 22 is accessible"
        else
            check_fail "SSH: Port 22 is not accessible" \
                "Check NSG rules: ssh $ADMIN_USERNAME@$VM_IP should work. Verify 'allowed_ssh_cidr' in terraform.tfvars"
        fi
    elif command -v timeout > /dev/null 2>&1; then
        # Fallback to timeout + bash TCP test
        if timeout 5 bash -c "cat < /dev/null > /dev/tcp/$VM_IP/22" 2>/dev/null; then
            check_pass "SSH: Port 22 is accessible"
        else
            check_fail "SSH: Port 22 is not accessible" \
                "Check NSG rules: ssh $ADMIN_USERNAME@$VM_IP should work. Verify 'allowed_ssh_cidr' in terraform.tfvars"
        fi
    else
        check_fail "SSH: Cannot test port 22 (nc/timeout not available)" \
            "Install netcat: sudo apt-get install netcat"
    fi
}

# =============================================================================
# Application Layer Checks
# =============================================================================

check_application_ports() {
    echo "Checking application layer..."
    
    # Service ports 8081-8084
    local services=("user-service:8081" "asset-service:8082" "portfolio-service:8083" "notification-service:8084")
    
    for service_port in "$${services[@]}"; do
        IFS=':' read -r service port <<< "$service_port"
        
        if command -v nc > /dev/null 2>&1; then
            if nc -z -w5 "$VM_IP" "$port" > /dev/null 2>&1; then
                check_pass "Application: $service port $port is accessible"
            else
                check_fail "Application: $service port $port is not accessible" \
                    "Service may still be starting. Check logs: ssh $ADMIN_USERNAME@$VM_IP 'docker logs markovitz-$service'"
            fi
        elif command -v timeout > /dev/null 2>&1; then
            if timeout 5 bash -c "cat < /dev/null > /dev/tcp/$VM_IP/$port" 2>/dev/null; then
                check_pass "Application: $service port $port is accessible"
            else
                check_fail "Application: $service port $port is not accessible" \
                    "Service may still be starting. Check logs: ssh $ADMIN_USERNAME@$VM_IP 'docker logs markovitz-$service'"
            fi
        else
            check_fail "Application: Cannot test $service port $port (nc/timeout not available)" \
                "Install netcat: sudo apt-get install netcat"
        fi
    done
    
    # RabbitMQ Management UI port 15672
    if command -v nc > /dev/null 2>&1; then
        if nc -z -w5 "$VM_IP" 15672 > /dev/null 2>&1; then
            check_pass "Application: RabbitMQ Management UI port 15672 is accessible"
        else
            check_fail "Application: RabbitMQ Management UI port 15672 is not accessible" \
                "Check logs: ssh $ADMIN_USERNAME@$VM_IP 'docker logs markovitz-rabbitmq'"
        fi
    elif command -v timeout > /dev/null 2>&1; then
        if timeout 5 bash -c "cat < /dev/null > /dev/tcp/$VM_IP/15672" 2>/dev/null; then
            check_pass "Application: RabbitMQ Management UI port 15672 is accessible"
        else
            check_fail "Application: RabbitMQ Management UI port 15672 is not accessible" \
                "Check logs: ssh $ADMIN_USERNAME@$VM_IP 'docker logs markovitz-rabbitmq'"
        fi
    else
        check_fail "Application: Cannot test RabbitMQ port 15672 (nc/timeout not available)" \
            "Install netcat: sudo apt-get install netcat"
    fi
}

# =============================================================================
# Health Endpoint Checks (HTTP)
# =============================================================================

check_health_endpoints() {
    echo "Checking health endpoints..."
    
    local services=("user-service:8081" "asset-service:8082" "portfolio-service:8083" "notification-service:8084")
    
    for service_port in "$${services[@]}"; do
        IFS=':' read -r service port <<< "$service_port"
        
        if command -v curl > /dev/null 2>&1; then
            local response
            response=$(curl -s -m 10 "http://$VM_IP:$port/actuator/health" 2>/dev/null || echo "")
            
            if echo "$response" | grep -q '"status":"UP"'; then
                check_pass "Health: $service is UP"
            else
                check_fail "Health: $service is not UP or unreachable" \
                    "Check bootstrap log: ssh $ADMIN_USERNAME@$VM_IP 'tail -100 /var/log/markovitz-bootstrap.log'"
            fi
        else
            check_fail "Health: Cannot test $service (curl not available)" \
                "Install curl: sudo apt-get install curl"
        fi
    done
}

# =============================================================================
# Swagger UI Checks (HTTP)
# =============================================================================

check_swagger_uis() {
    echo "Checking Swagger UIs..."
    
    local services=("user-service:8081" "asset-service:8082" "portfolio-service:8083" "notification-service:8084")
    
    for service_port in "$${services[@]}"; do
        IFS=':' read -r service port <<< "$service_port"
        
        if command -v curl > /dev/null 2>&1; then
            local status_code
            status_code=$(curl -s -o /dev/null -w "%%{http_code}" -m 10 "http://$VM_IP:$port/swagger-ui.html" 2>/dev/null || echo "000")
            
            if [ "$status_code" = "200" ]; then
                check_pass "Swagger UI: $service is accessible"
            else
                check_fail "Swagger UI: $service returned HTTP $status_code" \
                    "Service may still be initializing. Wait a few minutes or check: http://$VM_IP:$port/swagger-ui.html"
            fi
        else
            check_fail "Swagger UI: Cannot test $service (curl not available)" \
                "Install curl: sudo apt-get install curl"
        fi
    done
}

# =============================================================================
# RabbitMQ Management UI Check
# =============================================================================

check_rabbitmq_management() {
    echo "Checking RabbitMQ Management UI..."
    
    if command -v curl > /dev/null 2>&1; then
        local status_code
        status_code=$(curl -s -o /dev/null -w "%%{http_code}" -m 10 "http://$VM_IP:15672" 2>/dev/null || echo "000")
        
        if [ "$status_code" = "200" ]; then
            check_pass "RabbitMQ Management UI: Accessible at http://$VM_IP:15672"
        else
            check_fail "RabbitMQ Management UI: Returned HTTP $status_code" \
                "Check RabbitMQ container: ssh $ADMIN_USERNAME@$VM_IP 'docker logs markovitz-rabbitmq'"
        fi
    else
        check_fail "RabbitMQ Management UI: Cannot test (curl not available)" \
            "Install curl: sudo apt-get install curl"
    fi
}

# =============================================================================
# Main Execution
# =============================================================================

main() {
    print_header
    
    # Run all checks
    check_network_ping
    check_ssh_port
    check_application_ports
    check_health_endpoints
    check_swagger_uis
    check_rabbitmq_management
    
    # Print summary
    echo ""
    echo "=========================================="
    echo "  Verification Summary"
    echo "=========================================="
    echo "Total checks: $TOTAL_CHECKS"
    echo -e "Passed: $${GREEN}$PASSED_CHECKS$${NC}"
    echo -e "Failed: $${RED}$FAILED_CHECKS$${NC}"
    echo ""
    
    # Final result
    if [ "$FAILED_CHECKS" -eq 0 ]; then
        echo -e "$${GREEN}[SUCCESS]$${NC} Deploy verificado com sucesso"
        echo ""
        exit 0
    else
        echo -e "$${RED}[FAILURE]$${NC} Deploy verification failed"
        echo ""
        echo "Diagnostic commands:"
        echo "  - View bootstrap log: ssh $ADMIN_USERNAME@$VM_IP 'tail -100 /var/log/markovitz-bootstrap.log'"
        echo "  - Check containers: ssh $ADMIN_USERNAME@$VM_IP 'docker ps -a'"
        echo "  - Check resources: ssh $ADMIN_USERNAME@$VM_IP 'free -h && df -h'"
        echo ""
        exit 1
    fi
}

# Run main function
main
